CREATE TYPE product_category AS ENUM ('CONSOLE_GAME', 'MERCHANDISE', 'BOARD_GAME', 'ACCESSORY', 'CONSOLE', 'PC_HARDWARE');
CREATE TYPE product_condition AS ENUM ('NEW', 'USED');
CREATE TYPE tag_enum AS ENUM (
  'PS1', 'PS2', 'PS3', 'PS4', 'PS5',
  'PLAYSTATION', 'NINTENDO', 'NINTENDO_SWITCH',
  'WII', 'WIIU', 'XBOX', 'XBOX360',
  'XBOXONE', 'XBOXSERIESX', 'PC',
  'HORROR', 'ACTION', 'ADVENTURE',
  'RPG', 'STRATEGY', 'SIMULATION',
  'SPORTS', 'RACING'
);


CREATE TABLE IF NOT EXISTS public.product
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    average_rating double precision NOT NULL,
    category product_category NOT NULL,
    condition product_condition NOT NULL,
    description character varying(255),
    image_url character varying(255),
    name character varying(255),
    price double precision NOT NULL,
    stock integer NOT NULL
);

INSERT INTO public.product (id, average_rating, category, condition, description, image_url, name, price, stock) VALUES (3, 5, 'CONSOLE_GAME', 'NEW', 'string', 'string', 'string', 10000, 0);
INSERT INTO public.product (id, average_rating, category, condition, description, image_url, name, price, stock) VALUES (4, 5, 'CONSOLE_GAME', 'NEW', 'string', 'string', 'string', 10000, 0);
INSERT INTO public.product (id, average_rating, category, condition, description, image_url, name, price, stock) VALUES (5, 5, 'CONSOLE_GAME', 'NEW', 'string', 'string', 'string', 10000, 0);
INSERT INTO public.product (id, average_rating, category, condition, description, image_url, name, price, stock) VALUES (6, 5, 'CONSOLE_GAME', 'NEW', 'string', 'string', 'TEst', 10000, 0);
INSERT INTO public.product (id, average_rating, category, condition, description, image_url, name, price, stock) VALUES (7, 5, 'CONSOLE_GAME', 'NEW', 'string', 'string', 'string', 10000, 0);
INSERT INTO public.product (id, average_rating, category, condition, description, image_url, name, price, stock) VALUES (8, 5, 'CONSOLE_GAME', 'NEW', 'string', 'string', 'string', 10000, 0);
INSERT INTO public.product (id, average_rating, category, condition, description, image_url, name, price, stock) VALUES (9, 5, 'CONSOLE_GAME', 'NEW', 'string', 'string', 'string', 10000, 0);
INSERT INTO public.product (id, average_rating, category, condition, description, image_url, name, price, stock) VALUES (10, 5, 'CONSOLE_GAME', 'NEW', 'string', 'string', 'string', 10000, 0);
INSERT INTO public.product (id, average_rating, category, condition, description, image_url, name, price, stock) VALUES (11, 5, 'CONSOLE_GAME', 'NEW', 'string', 'string', 'string', 10000, 0);
INSERT INTO public.product (id, average_rating, category, condition, description, image_url, name, price, stock) VALUES (12, 5, 'CONSOLE_GAME', 'NEW', 'string', 'string', 'string', 10000, 0);
INSERT INTO public.product (id, average_rating, category, condition, description, image_url, name, price, stock) VALUES (13, 5, 'CONSOLE_GAME', 'NEW', 'string', 'string', 'string', 10000, 0);
INSERT INTO public.product (id, average_rating, category, condition, description, image_url, name, price, stock) VALUES (14, 5, 'CONSOLE_GAME', 'NEW', 'string', 'string', 'string', 10000, 0);

CREATE TABLE IF NOT EXISTS public.product_tags
(
    product_id BIGINT NOT NULL PRIMARY KEY,
    tags tag_enum NOT NULL,

    CONSTRAINT fk_product FOREIGN KEY (product_id)
    REFERENCES public.product (id) ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT product_tags_unique UNIQUE (product_id, tags)
);

INSERT INTO public.product_tags (product_id, tags) VALUES (3, 'PS1');
INSERT INTO public.product_tags (product_id, tags) VALUES (4, 'PS1');
INSERT INTO public.product_tags (product_id, tags) VALUES (6, 'PS1');
INSERT INTO public.product_tags (product_id, tags) VALUES (5, 'PS1');
INSERT INTO public.product_tags (product_id, tags) VALUES (7, 'PS1');
INSERT INTO public.product_tags (product_id, tags) VALUES (8, 'PS1');
INSERT INTO public.product_tags (product_id, tags) VALUES (9, 'PS1');
INSERT INTO public.product_tags (product_id, tags) VALUES (10, 'PS1');
INSERT INTO public.product_tags (product_id, tags) VALUES (11, 'PS1');
INSERT INTO public.product_tags (product_id, tags) VALUES (12, 'PS1');
INSERT INTO public.product_tags (product_id, tags) VALUES (13, 'PS1');
INSERT INTO public.product_tags (product_id, tags) VALUES (14, 'PS1');
