
CREATE TYPE public.orderstatus AS ENUM (
    'PENDING',
    'PAID',
    'SHIPPED',
    'DELIVERED'
);

CREATE TYPE public.product_category AS ENUM (
    'CONSOLE_GAME',
    'MERCHANDISE',
    'BOARD_GAME',
    'ACCESSORY',
    'CONSOLE',
    'PC_HARDWARE'
);



CREATE TYPE public.product_condition AS ENUM (
    'NEW',
    'USED'
);

CREATE TABLE public.order_item (
    id bigint NOT NULL,
    price double precision NOT NULL,
    quantity integer NOT NULL,
    order_id bigint NOT NULL,
    product_id bigint NOT NULL
);

ALTER TABLE public.order_item ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.order_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE public.orders (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    status character varying(255) DEFAULT 'PENDING'::public.orderstatus NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    price double precision NOT NULL
);

ALTER TABLE public.orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE public.product (
    id bigint NOT NULL,
    average_rating double precision NOT NULL,
    itemcategory character varying(255),
    itemcondition character varying(255),
    description character varying(255),
    image_url character varying(255),
    name character varying(255),
    price double precision NOT NULL,
    CONSTRAINT product_category_check CHECK (((itemcategory)::text = ANY (ARRAY[('CONSOLE_GAME'::character varying)::text, ('MERCHANDISE'::character varying)::text, ('BOARD_GAME'::character varying)::text, ('ACCESSORY'::character varying)::text, ('CONSOLE'::character varying)::text, ('PC_HARDWARE'::character varying)::text]))),
    CONSTRAINT product_condition_check CHECK (((itemcondition)::text = ANY (ARRAY[('NEW'::character varying)::text, ('USED'::character varying)::text])))
);


ALTER TABLE public.product ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE public.product_item_tags (
    product_id bigint NOT NULL,
    itemtags character varying(255),
    CONSTRAINT product_item_tags_itemtags_check CHECK (((itemtags)::text = ANY ((ARRAY['PS1'::character varying, 'PS2'::character varying, 'PS3'::character varying, 'PS4'::character varying, 'PS5'::character varying, 'PLAYSTATION'::character varying, 'NINTENDO'::character varying, 'NINTENDO_SWITCH'::character varying, 'WII'::character varying, 'WIIU'::character varying, 'XBOX'::character varying, 'XBOX360'::character varying, 'XBOXONE'::character varying, 'XBOXSERIESX'::character varying, 'PC'::character varying, 'HORROR'::character varying, 'ACTION'::character varying, 'ADVENTURE'::character varying, 'RPG'::character varying, 'STRATEGY'::character varying, 'SIMULATION'::character varying, 'SPORTS'::character varying, 'RACING'::character varying])::text[])))
);

CREATE TABLE public.product_tags (
    product_id bigint NOT NULL,
    itemtags character varying(255),
    CONSTRAINT product_tags_tags_check CHECK (((itemtags)::text = ANY ((ARRAY['PS1'::character varying, 'PS2'::character varying, 'PS3'::character varying, 'PS4'::character varying, 'PS5'::character varying, 'PLAYSTATION'::character varying, 'NINTENDO'::character varying, 'NINTENDO_SWITCH'::character varying, 'WII'::character varying, 'WIIU'::character varying, 'XBOX'::character varying, 'XBOX360'::character varying, 'XBOXONE'::character varying, 'XBOXSERIESX'::character varying, 'PC'::character varying, 'HORROR'::character varying, 'ACTION'::character varying, 'ADVENTURE'::character varying, 'RPG'::character varying, 'STRATEGY'::character varying, 'SIMULATION'::character varying, 'SPORTS'::character varying, 'RACING'::character varying])::text[])))
);

CREATE TABLE public.role (
    id bigint NOT NULL,
    name character varying(255)
);

ALTER TABLE public.role ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.stock (
    id bigint NOT NULL,
    warehouse_id bigint NOT NULL,
    product_id bigint NOT NULL,
    quantity integer DEFAULT 0 NOT NULL
);


ALTER TABLE public.stock ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stock_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.user_roles (
    user_id bigint NOT NULL,
    role_id bigint NOT NULL
);


CREATE TABLE public.users (
    id bigint NOT NULL,
    email character varying(255),
    password character varying(255),
    username character varying(255),
    CONSTRAINT users_email_unique UNIQUE (email),
    CONSTRAINT users_username_unique UNIQUE (username)
);

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.warehouse (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    location character varying(255),
    capacity bigint
);

ALTER TABLE public.warehouse ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.warehouse_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.order_item
    ADD CONSTRAINT order_item_pkey PRIMARY KEY (id);


ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.product
    ADD CONSTRAINT product_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.product
    ADD CONSTRAINT product_tags_unique UNIQUE (id);


ALTER TABLE ONLY public.role
    ADD CONSTRAINT role_pkey PRIMARY KEY (id);


ALTER TABLE ONLY public.stock
    ADD CONSTRAINT stock_pkey PRIMARY KEY (id);


ALTER TABLE ONLY public.stock
    ADD CONSTRAINT unique_product_warehouse UNIQUE (warehouse_id, product_id);


ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT user_roles_pkey PRIMARY KEY (user_id, role_id);


ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


ALTER TABLE ONLY public.warehouse
    ADD CONSTRAINT warehouse_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.product_item_tags
    ADD CONSTRAINT fk1uy8t98750rr9jki59d8yaxk FOREIGN KEY (product_id) REFERENCES public.product(id);


ALTER TABLE ONLY public.order_item
    ADD CONSTRAINT fk551losx9j75ss5d6bfsqvijna FOREIGN KEY (product_id) REFERENCES public.product(id);


ALTER TABLE ONLY public.product_tags
    ADD CONSTRAINT fk8gmf959fnpxtkagtk56mbaj0e FOREIGN KEY (product_id) REFERENCES public.product(id);


ALTER TABLE ONLY public.stock
    ADD CONSTRAINT fk_product FOREIGN KEY (product_id) REFERENCES public.product(id) ON UPDATE CASCADE ON DELETE CASCADE;


ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY public.stock
    ADD CONSTRAINT fk_warehouse FOREIGN KEY (warehouse_id) REFERENCES public.warehouse(id) ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fkhfh9dx7w3ubf1co1vdev94g3f FOREIGN KEY (user_id) REFERENCES public.users(id);



ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fkrhfovtciq1l558cw6udg0h0d3 FOREIGN KEY (role_id) REFERENCES public.role(id);



ALTER TABLE ONLY public.order_item
    ADD CONSTRAINT fkt4dc2r9nbvbujrljv3e23iibt FOREIGN KEY (order_id) REFERENCES public.orders(id);

