

INSERT INTO product (name, description, itemcondition, itemcategory, price, image_url, average_rating) VALUES
('PlayStation 5', 'Consola de última generación', 'NEW', 'CONSOLE', 49999, '', 5),
('Xbox Series X', 'Consola de nueva generación', 'NEW', 'CONSOLE', 49999, '', 5),
('Nintendo Switch', 'Consola portátil y de sobremesa', 'NEW', 'CONSOLE', 29999, '', 5),
('PS4 Pro', 'Consola PlayStation 4 Pro', 'USED', 'CONSOLE', 24999, '', 4),
('Xbox One X', 'Consola Xbox One X', 'USED', 'CONSOLE', 22999, '', 4),
('Wii U', 'Consola Nintendo Wii U', 'USED', 'CONSOLE', 12999, '', 4),
('PS3 Slim', 'Consola PlayStation 3', 'USED', 'CONSOLE', 9999, '', 4),
('Xbox 360', 'Consola Xbox 360', 'USED', 'CONSOLE', 7999, '', 3),
('PS2', 'Consola PlayStation 2', 'USED', 'CONSOLE', 4999, '', 3),
('PS1', 'Consola PlayStation 1', 'USED', 'CONSOLE', 2999, '', 3),
('The Last of Us Part II', 'Juego de acción y aventura', 'NEW', 'CONSOLE_GAME', 6999, '', 5),
('Resident Evil Village', 'Juego de horror y acción', 'NEW', 'CONSOLE_GAME', 6999, '', 5),
('FIFA 23', 'Juego de deportes', 'NEW', 'CONSOLE_GAME', 5999, '', 5),
('Mario Kart 8 Deluxe', 'Juego de carreras', 'NEW', 'CONSOLE_GAME', 4999, '', 5),
('Zelda: Breath of the Wild', 'Aventura RPG', 'NEW', 'CONSOLE_GAME', 6999, '', 5),
('Animal Crossing: New Horizons', 'Simulación y aventura', 'NEW', 'CONSOLE_GAME', 5999, '', 5),
('Call of Duty: Modern Warfare', 'Shooter de acción', 'NEW', 'CONSOLE_GAME', 6999, '', 5),
('Halo Infinite', 'Juego de acción para Xbox', 'NEW', 'CONSOLE_GAME', 6999, '', 5),
('Forza Horizon 5', 'Carreras de coches', 'NEW', 'CONSOLE_GAME', 6999, '', 5),
('Super Mario Odyssey', 'Aventura y plataformas', 'NEW', 'CONSOLE_GAME', 4999, '', 5),
('Merch camiseta Mario', 'Camiseta oficial de Mario', 'NEW', 'MERCHANDISE', 1999, '', 5),
('Merch gorra PlayStation', 'Gorra oficial PlayStation', 'NEW', 'MERCHANDISE', 1499, '', 5),
('Merch figura Zelda', 'Figura coleccionable', 'NEW', 'MERCHANDISE', 2499, '', 5),
('Merch taza Halo', 'Taza de colección', 'NEW', 'MERCHANDISE', 999, '', 5),
('Tablero Monopoly', 'Juego de mesa', 'NEW', 'BOARD_GAME', 3999, '', 5),
('Tablero Catan', 'Juego de estrategia', 'NEW', 'BOARD_GAME', 4499, '', 5),
('Accesorio DualSense', 'Mando PS5', 'NEW', 'ACCESSORY', 6999, '', 5),
('Accesorio Pro Controller', 'Mando Switch', 'NEW', 'ACCESSORY', 6999, '', 5),
('Accesorio Xbox Controller', 'Mando Xbox', 'NEW', 'ACCESSORY', 6999, '', 5),
('PC RTX 3080', 'Tarjeta gráfica', 'NEW', 'PC_HARDWARE', 89999, '', 5),
('PC Ryzen 9', 'Procesador AMD', 'NEW', 'PC_HARDWARE', 49999, '', 5),
('PC Intel i9', 'Procesador Intel', 'NEW', 'PC_HARDWARE', 59999, '', 5),
('PC RAM 16GB', 'Memoria RAM DDR4', 'NEW', 'PC_HARDWARE', 7999, '', 5),
('PC SSD 1TB', 'Disco SSD para PC', 'NEW', 'PC_HARDWARE', 11999, '', 5),
('PC Monitor 27"', 'Monitor Full HD', 'NEW', 'PC_HARDWARE', 15999, '', 5);

INSERT INTO product (name, description, itemcondition, itemcategory, price, image_url, average_rating) VALUES
('PS5 DualSense Controller', 'Mando inalámbrico para PS5', 'NEW', 'ACCESSORY', 6999, '', 5),
('Xbox Elite Series 2', 'Mando premium Xbox', 'NEW', 'ACCESSORY', 9999, '', 5),
('Switch Joy-Con Left', 'Mando izquierdo para Switch', 'NEW', 'ACCESSORY', 3999, '', 5),
('Switch Joy-Con Right', 'Mando derecho para Switch', 'NEW', 'ACCESSORY', 3999, '', 5),
('PS5 Pulse 3D Headset', 'Auriculares inalámbricos para PS5', 'NEW', 'ACCESSORY', 7999, '', 5),
('Xbox Series X Headset Adapter', 'Adaptador de auriculares Xbox', 'NEW', 'ACCESSORY', 1999, '', 5),
('PC GPU RTX 3090', 'Tarjeta gráfica de alto rendimiento', 'NEW', 'PC_HARDWARE', 149999, '', 5),
('PC CPU Ryzen 7', 'Procesador AMD Ryzen 7', 'NEW', 'PC_HARDWARE', 39999, '', 5),
('PC CPU Intel i7', 'Procesador Intel i7', 'NEW', 'PC_HARDWARE', 44999, '', 5),
('PC SSD 512GB', 'Disco SSD rápido', 'NEW', 'PC_HARDWARE', 6999, '', 5),
('Board Game Pandemic', 'Juego cooperativo de estrategia', 'NEW', 'BOARD_GAME', 3499, '', 5),
('Board Game Ticket to Ride', 'Juego de mesa clásico', 'NEW', 'BOARD_GAME', 2999, '', 5),
('Board Game Carcassonne', 'Juego de estrategia y colocación', 'NEW', 'BOARD_GAME', 2799, '', 5),
('Merch Hoodie Mario', 'Sudadera oficial de Mario', 'NEW', 'MERCHANDISE', 2999, '', 5),
('Merch Poster Zelda', 'Póster coleccionable', 'NEW', 'MERCHANDISE', 999, '', 5),
('Merch Keychain Xbox', 'Llavero oficial Xbox', 'NEW', 'MERCHANDISE', 499, '', 5),
('Merch Figure Samus', 'Figura coleccionable de Metroid', 'NEW', 'MERCHANDISE', 2499, '', 5),
('PS4 DualShock Controller', 'Mando PS4', 'USED', 'ACCESSORY', 3999, '', 4),
('Xbox One Controller', 'Mando Xbox One', 'USED', 'ACCESSORY', 3999, '', 4),
('Switch Pro Dock', 'Base para Nintendo Switch', 'NEW', 'ACCESSORY', 2999, '', 5),
('PC Monitor 32"', 'Monitor gaming 4K', 'NEW', 'PC_HARDWARE', 19999, '', 5),
('PC RAM 32GB', 'Memoria RAM DDR4', 'NEW', 'PC_HARDWARE', 14999, '', 5),
('PC Liquid Cooler', 'Sistema de refrigeración líquida', 'NEW', 'PC_HARDWARE', 7999, '', 5),
('PS5 Media Remote', 'Control remoto multimedia', 'NEW', 'ACCESSORY', 1999, '', 5),
('Xbox Charging Cable', 'Cable de carga para mando Xbox', 'NEW', 'ACCESSORY', 999, '', 5),
('Switch Carry Case', 'Estuche portátil para Switch', 'NEW', 'ACCESSORY', 1499, '', 5),
('Board Game Splendor', 'Juego de estrategia económica', 'NEW', 'BOARD_GAME', 2499, '', 5),
('Board Game Azul', 'Juego de mesa estratégico', 'NEW', 'BOARD_GAME', 2299, '', 5),
('Merch Poster Halo', 'Póster oficial Halo', 'NEW', 'MERCHANDISE', 999, '', 5),
('Merch Hoodie PlayStation', 'Sudadera oficial PS', 'NEW', 'MERCHANDISE', 2999, '', 5),
('FIFA 22', 'Juego de deportes para PS4', 'USED', 'CONSOLE_GAME', 3999, '', 4),
('Madden NFL 23', 'Juego de deportes americano', 'NEW', 'CONSOLE_GAME', 4999, '', 5),
('Super Smash Bros', 'Juego de lucha para Switch', 'NEW', 'CONSOLE_GAME', 4999, '', 5),
('Legend of Zelda: Link’s Awakening', 'Aventura clásica', 'USED', 'CONSOLE_GAME', 3999, '', 5),
('Pokemon Sword', 'Juego RPG de Pokémon', 'NEW', 'CONSOLE_GAME', 5999, '', 5),
('Pokemon Shield', 'Juego RPG de Pokémon', 'NEW', 'CONSOLE_GAME', 5999, '', 5);

INSERT INTO product (name, description, itemcondition, itemcategory, price, image_url, average_rating) VALUES
('God of War Ragnarok', 'Juego de acción-aventura PS5', 'NEW', 'CONSOLE_GAME', 6999, '', 5),
('Horizon Forbidden West', 'Aventura y acción para PS5', 'NEW', 'CONSOLE_GAME', 6999, '', 5),
('Gran Turismo 7', 'Juego de carreras PS5', 'NEW', 'CONSOLE_GAME', 6999, '', 5),
('Forza Motorsport 7', 'Juego de carreras Xbox', 'NEW', 'CONSOLE_GAME', 6999, '', 5),
('Mario Party Superstars', 'Juego de fiesta Switch', 'NEW', 'CONSOLE_GAME', 4999, '', 5),
('Metroid Dread', 'Aventura y acción Switch', 'NEW', 'CONSOLE_GAME', 5999, '', 5),
('Luigi’s Mansion 3', 'Aventura y puzzles Switch', 'NEW', 'CONSOLE_GAME', 4999, '', 5),
('Kirby and the Forgotten Land', 'Plataformas Switch', 'NEW', 'CONSOLE_GAME', 4999, '', 5),
('PS5 Console Stand', 'Soporte vertical para PS5', 'NEW', 'ACCESSORY', 1499, '', 5),
('Xbox Series X Stand', 'Soporte vertical para Xbox', 'NEW', 'ACCESSORY', 1499, '', 5),
('Switch Pro Controller', 'Mando profesional Switch', 'NEW', 'ACCESSORY', 6999, '', 5),
('PS5 Controller Charger', 'Cargador dual para mandos PS5', 'NEW', 'ACCESSORY', 2499, '', 5),
('Xbox Rechargeable Battery', 'Batería recargable mando Xbox', 'NEW', 'ACCESSORY', 1499, '', 5),
('PC Gaming Chair', 'Silla ergonómica para gaming', 'NEW', 'ACCESSORY', 19999, '', 5),
('PC Mechanical Keyboard', 'Teclado mecánico RGB', 'NEW', 'ACCESSORY', 7999, '', 5),
('PC Gaming Mouse', 'Ratón para juegos', 'NEW', 'ACCESSORY', 3999, '', 5),
('Board Game Chess Deluxe', 'Ajedrez edición de lujo', 'NEW', 'BOARD_GAME', 1999, '', 5),
('Board Game Risk', 'Juego de estrategia bélica', 'NEW', 'BOARD_GAME', 2499, '', 5),
('Board Game Monopoly Junior', 'Versión infantil de Monopoly', 'NEW', 'BOARD_GAME', 1499, '', 5),
('Merch PS5 Hoodie', 'Sudadera oficial PlayStation 5', 'NEW', 'MERCHANDISE', 2999, '', 5),
('Merch Xbox Hoodie', 'Sudadera oficial Xbox Series X', 'NEW', 'MERCHANDISE', 2999, '', 5),
('Merch Mario Hat', 'Gorra oficial Mario', 'NEW', 'MERCHANDISE', 1499, '', 5),
('Merch Zelda Figure', 'Figura coleccionable Zelda', 'NEW', 'MERCHANDISE', 2499, '', 5),
('Merch Pikachu Plush', 'Peluche oficial Pikachu', 'NEW', 'MERCHANDISE', 1999, '', 5),
('PC GPU RTX 3080 Ti', 'Tarjeta gráfica de alto rendimiento', 'NEW', 'PC_HARDWARE', 129999, '', 5),
('PC CPU Ryzen 9 5900X', 'Procesador AMD Ryzen 9', 'NEW', 'PC_HARDWARE', 69999, '', 5),
('PC CPU Intel i9 12900K', 'Procesador Intel i9 de última generación', 'NEW', 'PC_HARDWARE', 74999, '', 5),
('PC RAM 64GB', 'Memoria RAM DDR4 para gaming', 'NEW', 'PC_HARDWARE', 24999, '', 5),
('PC NVMe SSD 2TB', 'Disco NVMe rápido', 'NEW', 'PC_HARDWARE', 29999, '', 5),
('PC Monitor Ultrawide 34"', 'Monitor panorámico 144Hz', 'NEW', 'PC_HARDWARE', 25999, '', 5);
